name: Automatic evaluator
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator:
    runs-on: self-hosted
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch Flake8 linter
        uses: actions/checkout@v2
        with:
          repository: betrybe/flake8-linter-action
          ref: v1.3
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/flake8-linter

      - name: Fetch PyTest evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/pytest-evaluator-action
          ref: v5
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/pytest-evaluator

      - name: Fetch Store evaluation
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v7
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: "14"

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: "main"

      - name: Set Python Version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.1"

      - name: Run Flake8 linter
        id: flake8_linter
        uses: ./.github/actions/flake8-linter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}

      - name: Run PyTest evaluation
        id: evaluator
        uses: ./.github/actions/pytest-evaluator
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}
        env:
          DB_HOST: "mongodb"
          DB_PORT: "27017"

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          token: ${{ secrets.GITHUB_TOKEN }}
